spring:
  datasource:
    url: jdbc:postgresql://db:5432/itil_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 8080